version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: onidolus_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onidolus
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 